CREATE TABLE IF NOT EXISTS sales.customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL CHECK (btrim(full_name) <> ''),
    email TEXT NOT NULL UNIQUE CHECK (position('@' IN email) > 1),
    country TEXT,
    signup_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales.products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL CHECK (btrim(product_name) <> ''),
    category TEXT NOT NULL CHECK (btrim(category) <> ''),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sales.orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES sales.customers(customer_id),
    order_status TEXT NOT NULL CHECK (order_status IN ('pending', 'paid', 'shipped', 'cancelled')),
    ordered_at TIMESTAMPTZ NOT NULL,
    shipping_country TEXT
);

CREATE TABLE IF NOT EXISTS sales.order_items (
    order_id BIGINT NOT NULL REFERENCES sales.orders(order_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES sales.products(product_id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    discount_pct NUMERIC(5, 2) NOT NULL DEFAULT 0 CHECK (discount_pct BETWEEN 0 AND 100),
    PRIMARY KEY (order_id, product_id)
);

COMMENT ON TABLE sales.orders IS 'One row per customer order';
COMMENT ON TABLE sales.order_items IS 'Order line items; unit_price is the historical sale price';

