-- Run in a disposable schema if experimenting with DDL.
CREATE TABLE IF NOT EXISTS lab.inventory_reservations (
    reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES sales.orders(order_id),
    product_id BIGINT NOT NULL REFERENCES sales.products(product_id),
    reserved_quantity INTEGER NOT NULL CHECK (reserved_quantity > 0),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'released', 'fulfilled')),
    UNIQUE (order_id, product_id)
);

COMMENT ON TABLE lab.inventory_reservations IS 'Small DDL exercise table; safe to drop in the lab schema.';

